apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        default_type text/html;

        location /stuff.html {
            root /usr/share/nginx/html;
        }

        location / {
            return 200 '<!DOCTYPE html>
    <html>
    <head>
    <title>$request_uri - $hostname</title>
    </head>
    You\'ve requested the URL <pre>$request_uri</pre>
    Your request has been processed by this pod<pre>$hostname</pre>
    Your ELB:<br>
    <iframe height="200" width="600" src="stuff.html"></iframe>
    </html>';
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-09T16:21:41Z"
  name: defaultconf
  namespace: default
  resourceVersion: "2439273"
  selfLink: /api/v1/namespaces/default/configmaps/defaultconf
  uid: 0f929025-6222-11ea-a8a1-02f3d5fa2a08
---
apiVersion: v1
data:
  script.sh: |
    #!/bin/bash

    elb='elb.amazonaws.com'

    curloutput=$( \
    curl \
    -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
    --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
    -XGET \
    -H "Accept: application/json" \
    -s \
    https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/ingress-nginx/services/ingress-nginx \
    )

    if [[ "$curloutput" == *"$elb"* ]]
    then
      echo $curloutput | jq .status.loadBalancer.ingress[].hostname > /work-dir/stuff.html
    else
      echo $curloutput | jq .message > /work-dir/stuff.html
    fi
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-20T20:44:02Z"
  name: scriptdir
  namespace: default
  resourceVersion: "5177002"
  selfLink: /api/v1/namespaces/default/configmaps/workdir
  uid: 88240e9f-6aeb-11ea-ba7e-0a2662574af4
